# data_config.yaml
# Data path configurations and parameters for the tennis stroke detection pipeline

# Data directory paths
data_paths:
  base_dir: "data"
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  processed_dir: "data/processed"
  external_dir: "data/external"
  models_dir: "models"
  
# Video processing settings
video:
  target_fps: 30
  resize_width: 1280
  resize_height: 720
  min_duration: 2.0  # Minimum duration of a stroke in seconds
  max_duration: 5.0  # Maximum duration of a stroke in seconds

# Dataset settings
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_size: 32
  shuffle: true
  num_workers: 4
  random_seed: 42

# Label definitions
labels:
  stroke_types:
    - "forehand"
    - "backhand"
    - "serve"
    - "volley"
    - "smash"
  
  difficulty_levels:
    - "beginner"
    - "intermediate"
    - "advanced"
    - "professional"