# model_config.yaml
# Controls hyperparameters, architecture type, and other model settings.

model:
  type: "LSTM"   # or 'Transformer' or 'CNN-RNN' etc.
  hidden_size: 256
  num_layers: 2
  dropout: 0.2
  bidirectional: true

optimizer:
  type: "adam"
  lr: 0.001
  weight_decay: 1e-5

loss_function: "cross_entropy"

metrics:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"

# If you’re using pretrained weights or transfer learning:
pretrained: false
pretrained_weights_path: "path/to/pretrained.pt"