# segmentation_config.yaml
# Configuration for stroke segmentation and clip generation

# Directory paths
paths:
  processed_dir: "videos/processed"  # Processed data and LLC files
  strokes_dir: "videos/strokes"      # Final stroke clips and data

# Stroke processing settings
stroke:
  resampled_frames: 120  # Number of frames after time normalization
  force_reprocess: false  # If true, re-process even if files exist
  padding_seconds: 0.5  # Padding around each stroke segment

# Clip generation settings
clips:
  output_format: "mp4"
  resize_output: true
  width: 720
  height: 480
  generate_skeleton: true  # Generate skeleton overlay
  generate_overlay: true   # Generate pose overlay

# File naming
files:
  raw_csv: "raw.csv"
  normalized_csv: "normalized.csv"
  video_clip: "video.mp4"
  skeleton_clip: "skeleton.mp4"
  overlay_clip: "overlay.mp4" 