# pipeline_config.yaml
# Configuration for the tennis stroke detection pipeline

# Pipeline steps configuration
pipeline:
  - name: "pre_cut_processing"
    enabled: true
    description: "Pre-cut video processing pipeline"
    steps:
      - name: "download_videos"
        enabled: true
        description: "Download and convert videos to 30 FPS"
        params:
          source_type: "youtube"
          convert_to_mp4: true
          target_fps: 30

      - name: "pose_extraction"
        enabled: true
        description: "Extract pose landmarks using MediaPipe"
        params:
          model: "POSE_LANDMARK_FULL"
          min_detection_confidence: 0.5
          min_tracking_confidence: 0.5
          static_image_mode: false
          extract_hands: true
          extract_face: false

      - name: "normalization"
        enabled: true
        description: "Normalize pose data spatially"
        params:
          spatial_normalization: true
          smoothing_window: 5

  - name: "post_cut_processing"
    enabled: true
    description: "Post-cut processing pipeline"
    steps:
      - name: "feature_engineering"
        enabled: true
        description: "Add stroke labels based on LLC files"
        params:
          calculate_angles: true
          calculate_velocities: true

      - name: "clip_generation"
        enabled: true
        description: "Generate video clips from labeled segments"
        params:
          padding_seconds: 0.5
          output_format: "mp4"
          resize_output: true
          width: 720
          height: 480

      - name: "time_normalization"
        enabled: true
        description: "Normalize clip timelines to fixed number of frames"
        params:
          target_frames: 120
          interpolation_method: "linear"

# Global settings
settings:
  log_level: "INFO"
  num_workers: 4
  random_seed: 42
  save_interim_results: true

# Data directory paths
data_paths:
  processed_dir: "data/processed"  # Normalized data and LLC files
  final_library: "Final library"  # Final stroke clips and data

# Stroke segmentation settings
segmentation:
  resampled_frames: 120  # Number of frames after time normalization
  force_reprocess: false  # If true, re-process even if files exist
  padding_seconds: 0.5  # Padding around each stroke segment

# Clip generation settings
clips:
  output_format: "mp4"
  resize_output: true
  width: 720
  height: 480