# video_processing_config.yaml
# Configuration for video processing and pose extraction pipeline

# Data directory paths
data_paths:
  base_dir: "data"
  raw_dir: "data/raw"          # Raw videos downloaded from YouTube
  interim_dir: "data/interim"  # Intermediate pose data
  processed_dir: "data/processed"  # Normalized data and LLC files

# Video processing settings
video:
  target_fps: 30
  resize_width: 1280
  resize_height: 720

# Pose extraction settings
pose:
  calculate_angles: true
  num_processes: 8  # Maximum parallel workers for pose extraction

# Post-cut processing settings
post_cut:
  resampled_frames: 120  # Number of frames after time normalization
  force_reprocess: false  # If true, re-process even if files exist